# Generated by Django 6.0.5 on 2026-05-21 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_universityimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='The announcement text to display in the carousel')),
                ('link', models.CharField(blank=True, help_text='Optional link to redirect when clicked', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Toggle to show/hide this announcement')),
                ('order', models.IntegerField(default=0, help_text='Order in the carousel (lower numbers first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
