# Generated by Django 4.2.30 on 2026-08-11 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_course_contactlead_answers_coursequestion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(help_text='URL friendly name. e.g. mbbs', unique=True)),
                ('heading', models.CharField(default='Study Program', max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='programs/')),
                ('paragraph', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WhyGruniBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(choices=[('Globe', 'Globe'), ('Building2', 'Building'), ('Briefcase', 'Briefcase'), ('ShieldCheck', 'Shield Check'), ('Award', 'Award'), ('Users', 'Users')], default='Globe', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Why Gruni Badge',
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='universityimage',
            options={'ordering': ['category', 'order']},
        ),
        migrations.AddField(
            model_name='university',
            name='campus_heading',
            field=models.CharField(default='Campus Life', max_length=255),
        ),
        migrations.AddField(
            model_name='university',
            name='campus_paragraph',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='founder_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='founder_paragraph',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='founder_pic',
            field=models.ImageField(blank=True, null=True, upload_to='universities/founder/'),
        ),
        migrations.AddField(
            model_name='university',
            name='georgia_heading',
            field=models.CharField(default='Georgia & Tbilisi', max_length=255),
        ),
        migrations.AddField(
            model_name='university',
            name='georgia_paragraph',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='georgia_photo',
            field=models.ImageField(blank=True, null=True, upload_to='universities/georgia/'),
        ),
        migrations.AddField(
            model_name='university',
            name='hospital_heading',
            field=models.CharField(default='Pino Hospital', max_length=255),
        ),
        migrations.AddField(
            model_name='university',
            name='hospital_paragraph',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='hostel_heading',
            field=models.CharField(default='Hostel', max_length=255),
        ),
        migrations.AddField(
            model_name='university',
            name='hostel_paragraph',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='universityimage',
            name='category',
            field=models.CharField(choices=[('GEORGIA', 'Georgia & Tbilisi'), ('MAIN', 'Main University'), ('HOSPITAL', 'Pino Hospital'), ('CAMPUS', 'Campus Life'), ('HOSTEL', 'Hostel')], default='MAIN', max_length=20),
        ),
        migrations.CreateModel(
            name='ProgramKeyPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(choices=[('Globe', 'Globe'), ('Building2', 'Building'), ('Briefcase', 'Briefcase'), ('ShieldCheck', 'Shield Check'), ('Award', 'Award'), ('Users', 'Users'), ('MapPin', 'Map Pin'), ('GraduationCap', 'Graduation Cap'), ('BookOpen', 'Book'), ('CheckCircle2', 'Check Circle')], default='CheckCircle2', max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_points', to='api.program')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProgramComparisonMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(help_text='e.g., Duration, Total Cost', max_length=100)),
                ('india_value', models.CharField(help_text='e.g., 5.5 Years', max_length=100)),
                ('georgia_value', models.CharField(help_text='e.g., 6 Years', max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparison_metrics', to='api.program')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProgramBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(choices=[('Globe', 'Globe'), ('Building2', 'Building'), ('Briefcase', 'Briefcase'), ('ShieldCheck', 'Shield Check'), ('Award', 'Award'), ('Users', 'Users'), ('HeartPulse', 'Heart Pulse'), ('Microscope', 'Microscope'), ('Stethoscope', 'Stethoscope'), ('BookOpen', 'Book')], default='Globe', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='api.program')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GeorgiaKeyPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(choices=[('Globe', 'Globe'), ('Building2', 'Building'), ('Briefcase', 'Briefcase'), ('ShieldCheck', 'Shield Check'), ('Award', 'Award'), ('Users', 'Users'), ('MapPin', 'Map Pin'), ('GraduationCap', 'Graduation Cap'), ('BookOpen', 'Book')], default='MapPin', max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='georgia_key_points', to='api.university')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
