# Generated by Django 6.0.5 on 2026-08-20 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_program_whygrunibadge_alter_universityimage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='team/')),
                ('badge_text', models.CharField(default='Official Representative', max_length=100)),
                ('subtitle', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('is_primary', models.BooleanField(default=False, help_text='Set true for the primary representative to use the gold theme.')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='VirtualTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=255)),
                ('title_ge', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='virtual_tours/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Virtual Tour',
                'ordering': ['order'],
            },
        ),
    ]
