# Generated by Django 6.0.5 on 2026-08-21 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_teammember_virtualtour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactlead',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
